/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizationsOrganizationIdRouteImport } from './routes/organizations.$organizationId'
import { Route as OrganizationsOrganizationIdMembersRouteImport } from './routes/organizations.$organizationId.members'
import { Route as ApiAdminSplatRouteImport } from './routes/api/admin/$'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsOrganizationIdRoute =
  OrganizationsOrganizationIdRouteImport.update({
    id: '/$organizationId',
    path: '/$organizationId',
    getParentRoute: () => OrganizationsRoute,
  } as any)
const OrganizationsOrganizationIdMembersRoute =
  OrganizationsOrganizationIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => OrganizationsOrganizationIdRoute,
  } as any)
const ApiAdminSplatRoute = ApiAdminSplatRouteImport.update({
  id: '/api/admin/$',
  path: '/api/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/support': typeof SupportRoute
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdRouteWithChildren
  '/api/admin/$': typeof ApiAdminSplatRoute
  '/organizations/$organizationId/members': typeof OrganizationsOrganizationIdMembersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/support': typeof SupportRoute
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdRouteWithChildren
  '/api/admin/$': typeof ApiAdminSplatRoute
  '/organizations/$organizationId/members': typeof OrganizationsOrganizationIdMembersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/support': typeof SupportRoute
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdRouteWithChildren
  '/api/admin/$': typeof ApiAdminSplatRoute
  '/organizations/$organizationId/members': typeof OrganizationsOrganizationIdMembersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/organizations'
    | '/support'
    | '/organizations/$organizationId'
    | '/api/admin/$'
    | '/organizations/$organizationId/members'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/organizations'
    | '/support'
    | '/organizations/$organizationId'
    | '/api/admin/$'
    | '/organizations/$organizationId/members'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/organizations'
    | '/support'
    | '/organizations/$organizationId'
    | '/api/admin/$'
    | '/organizations/$organizationId/members'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DashboardRoute: typeof DashboardRoute
  OrganizationsRoute: typeof OrganizationsRouteWithChildren
  SupportRoute: typeof SupportRoute
  ApiAdminSplatRoute: typeof ApiAdminSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationId': {
      id: '/organizations/$organizationId'
      path: '/$organizationId'
      fullPath: '/organizations/$organizationId'
      preLoaderRoute: typeof OrganizationsOrganizationIdRouteImport
      parentRoute: typeof OrganizationsRoute
    }
    '/organizations/$organizationId/members': {
      id: '/organizations/$organizationId/members'
      path: '/members'
      fullPath: '/organizations/$organizationId/members'
      preLoaderRoute: typeof OrganizationsOrganizationIdMembersRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRoute
    }
    '/api/admin/$': {
      id: '/api/admin/$'
      path: '/api/admin/$'
      fullPath: '/api/admin/$'
      preLoaderRoute: typeof ApiAdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OrganizationsOrganizationIdRouteChildren {
  OrganizationsOrganizationIdMembersRoute: typeof OrganizationsOrganizationIdMembersRoute
}

const OrganizationsOrganizationIdRouteChildren: OrganizationsOrganizationIdRouteChildren =
  {
    OrganizationsOrganizationIdMembersRoute:
      OrganizationsOrganizationIdMembersRoute,
  }

const OrganizationsOrganizationIdRouteWithChildren =
  OrganizationsOrganizationIdRoute._addFileChildren(
    OrganizationsOrganizationIdRouteChildren,
  )

interface OrganizationsRouteChildren {
  OrganizationsOrganizationIdRoute: typeof OrganizationsOrganizationIdRouteWithChildren
}

const OrganizationsRouteChildren: OrganizationsRouteChildren = {
  OrganizationsOrganizationIdRoute:
    OrganizationsOrganizationIdRouteWithChildren,
}

const OrganizationsRouteWithChildren = OrganizationsRoute._addFileChildren(
  OrganizationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DashboardRoute: DashboardRoute,
  OrganizationsRoute: OrganizationsRouteWithChildren,
  SupportRoute: SupportRoute,
  ApiAdminSplatRoute: ApiAdminSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
